import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { RoomType, RoomTypeDocument } from './schemas/room-type.schema';

const SEED_ROOM_TYPES = [
  // --- Interior Spaces ---
  {
    slug: 'living-room',
    name: 'Living room',
    category: 'interior',
    description: 'Transform modern living spaces with custom sofa layouts, coffee tables, wall art, and ambient lighting.',
    icon: 'Sofa',
    popularStyles: ['Modern', 'Japandi', 'Scandinavian', 'Industrial', 'Luxury', 'Boho'],
    compatibleToolSlugs: ['interior-design', 'ai-room-decorator', 'paint-color-visualizer', 'change-furniture-ai'],
  },
  {
    slug: 'open-kitchen-living',
    name: 'Open Kitchen Living Room',
    category: 'interior',
    description: 'Seamless open-concept layout connecting living, dining, and kitchen spaces.',
    icon: 'Layout',
    popularStyles: ['Modern Japandi', 'Contemporary Open', 'Scandinavian'],
    compatibleToolSlugs: ['interior-design', 'ai-room-decorator', 'kitchen-design'],
  },
  {
    slug: 'bedroom',
    name: 'Bedroom',
    category: 'interior',
    description: 'Design cozy, peaceful bedrooms with upholstered headboards, soft neutral tones, and warm bedside lighting.',
    icon: 'Bed',
    popularStyles: ['Cozy Japandi', 'Modern Luxury', 'Minimalist Neutral', 'Boho Chic'],
    compatibleToolSlugs: ['bedroom-design', 'interior-design', 'paint-color-visualizer', 'change-room-light'],
  },
  {
    slug: 'guest-bedroom',
    name: 'Guest Bedroom',
    category: 'interior',
    description: 'Welcoming, comfortable guest bedrooms equipped with fresh linens, side tables, and relaxed aesthetics.',
    icon: 'BedDouble',
    popularStyles: ['Scandinavian', 'Minimalist', 'Cozy Warmth'],
    compatibleToolSlugs: ['bedroom-design', 'interior-design'],
  },
  {
    slug: 'kids-room',
    name: 'Kids Room',
    category: 'interior',
    description: 'Playful, vibrant kids bedrooms with bunk beds, study corners, and creative wall murals.',
    icon: 'Smile',
    popularStyles: ['Playful Pastel', 'Modern Scandinavian Kids', 'Adventure Theme'],
    compatibleToolSlugs: ['bedroom-design', 'interior-design', 'paint-color-visualizer'],
  },
  {
    slug: 'nursery',
    name: 'Nursery',
    category: 'interior',
    description: 'Gentle, serene infant nurseries featuring cribs, rocking chairs, plush rugs, and soft pastel colors.',
    icon: 'Baby',
    popularStyles: ['Boho Neutral', 'Soft Pastel', 'Nordic Minimalist'],
    compatibleToolSlugs: ['bedroom-design', 'interior-design'],
  },
  {
    slug: 'bathroom',
    name: 'Bathroom',
    category: 'interior',
    description: 'Reimagine bathrooms as luxury spa retreats with walk-in glass showers, freestanding tubs, and marble vanities.',
    icon: 'ShowerHead',
    popularStyles: ['Modern Spa', 'Marble Luxury', 'Minimalist Tile', 'Rustic Wood'],
    compatibleToolSlugs: ['bathroom-design', 'interior-design', 'paint-color-visualizer', 'ai-flooring-design'],
  },
  {
    slug: 'kitchen',
    name: 'Kitchen',
    category: 'interior',
    description: 'Create chef-worthy kitchens with custom marble countertops, island seating, tile backsplashes, and cabinetry.',
    icon: 'Utensils',
    popularStyles: ['Modern Marble', 'Farmhouse', 'Minimalist Wood', 'Industrial Metallic'],
    compatibleToolSlugs: ['kitchen-design', 'interior-design', 'paint-color-visualizer'],
  },
  {
    slug: 'dining-room',
    name: 'Dining room',
    category: 'interior',
    description: 'Design elegant dining rooms featuring statement chandeliers, wooden dining tables, and accent walls.',
    icon: 'Wine',
    popularStyles: ['Modern Scandinavian', 'Mid-Century Modern', 'Classic Elegance'],
    compatibleToolSlugs: ['interior-design', 'ai-wall-design', 'change-furniture-ai'],
  },
  {
    slug: 'formal-dining',
    name: 'Formal Dining Room',
    category: 'interior',
    description: 'Sophisticated dining halls for formal hosting, grand tables, and ambient chandeliers.',
    icon: 'Sparkles',
    popularStyles: ['Classic Elegance', 'Modern Glam', 'Luxury Wood'],
    compatibleToolSlugs: ['interior-design', 'change-furniture-ai'],
  },
  {
    slug: 'attic',
    name: 'Attic',
    category: 'interior',
    description: 'Convert skylit attic spaces into cozy reading nooks, bedrooms, or creative studios.',
    icon: 'Home',
    popularStyles: ['Rustic Wood', 'Cozy Loft', 'Scandinavian Attic'],
    compatibleToolSlugs: ['interior-design', 'change-furniture-ai'],
  },
  {
    slug: 'study-room',
    name: 'Study room',
    category: 'interior',
    description: 'Quiet study sanctuaries with built-in bookshelves, reading lamps, and focused task desks.',
    icon: 'BookOpen',
    popularStyles: ['Academic Dark Wood', 'Minimalist Modern', 'Scandinavian Study'],
    compatibleToolSlugs: ['office-design', 'interior-design'],
  },
  {
    slug: 'home-office',
    name: 'Home office',
    category: 'interior',
    description: 'Build productive home workspaces with executive desks, ergonomic seating, and warm lighting.',
    icon: 'Briefcase',
    popularStyles: ['Ergonomic Modern', 'Industrial Loft', 'Executive Dark Leather'],
    compatibleToolSlugs: ['office-design', 'interior-design', 'change-furniture-ai'],
  },
  {
    slug: 'family-room',
    name: 'Family Room',
    category: 'interior',
    description: 'Spacious family gathering areas with sectional sofas, media centers, and kid-friendly layouts.',
    icon: 'Users',
    popularStyles: ['Cozy Family', 'Contemporary Warm', 'Bohemian Family'],
    compatibleToolSlugs: ['interior-design', 'ai-room-decorator'],
  },
  {
    slug: 'gaming-room',
    name: 'Gaming room',
    category: 'interior',
    description: 'Immersive gaming setups with RGB ambient neon strip lights, acoustic wall panels, and dual-monitor desks.',
    icon: 'Gamepad2',
    popularStyles: ['Cyberpunk RGB', 'Futuristic Dark Mode', 'Minimalist Gamer'],
    compatibleToolSlugs: ['interior-design', 'change-room-light'],
  },
  {
    slug: 'home-theater',
    name: 'Home Theater',
    category: 'interior',
    description: 'Cinematic entertainment rooms featuring plush leather recliners, projector screens, and acoustic carpeting.',
    icon: 'Film',
    popularStyles: ['Modern Cinema', 'Dark Luxury', 'Atmospheric Neon'],
    compatibleToolSlugs: ['interior-design', 'change-room-light'],
  },
  {
    slug: 'laundry-room',
    name: 'Laundry Room',
    category: 'interior',
    description: 'Organized, functional laundry rooms with custom cabinetry, folding countertops, and bright tiling.',
    icon: 'Shirt',
    popularStyles: ['Clean White', 'Modern Farmhouse', 'Minimalist Utility'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'utility-room',
    name: 'Utility Room',
    category: 'interior',
    description: 'Practical storage and utility spaces optimized with shelving, cabinets, and durable surfaces.',
    icon: 'Boxes',
    popularStyles: ['Industrial Practical', 'Clean Modern', 'Minimalist'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'pet-room',
    name: 'Pet Room',
    category: 'interior',
    description: 'Dedicated pet stations complete with custom grooming sinks, bed nooks, and toy storage.',
    icon: 'Dog',
    popularStyles: ['Cozy Wood', 'Playful Modern', 'Minimalist Tile'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'lounge',
    name: 'Lounge',
    category: 'interior',
    description: 'Relaxing lounge spaces featuring comfortable seating, low cocktail tables, and soft mood lighting.',
    icon: 'Armchair',
    popularStyles: ['Modern Luxury', 'Mid-Century Velvet', 'Boho Lounge'],
    compatibleToolSlugs: ['interior-design', 'change-furniture-ai'],
  },
  {
    slug: 'walk-in-closet',
    name: 'Walk-in Closet',
    category: 'interior',
    description: 'Boutique-style walk-in closets with LED illuminated glass display shelving, shoe racks, and vanity islands.',
    icon: 'Shirt',
    popularStyles: ['Luxury Dressing', 'Modern Minimalist', 'Warm Wood Boutique'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'playroom',
    name: 'Playroom',
    category: 'interior',
    description: 'Vibrant activity playrooms with toy organizers, climbing structures, soft floor mats, and creative wall art.',
    icon: 'Gamepad',
    popularStyles: ['Colorful Scandinavian', 'Montessori Neutral', 'Playful Theme'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'reading-nook',
    name: 'Reading Nook',
    category: 'interior',
    description: 'Cozy alcoves with built-in bench seating, plush cushions, warm reading lamps, and surrounding bookshelves.',
    icon: 'Book',
    popularStyles: ['Cozy Window Nook', 'Rustic Library', 'Minimalist Zen'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'sauna',
    name: 'Sauna',
    category: 'interior',
    description: 'Tranquil Finnish wooden saunas with cedar slatted walls, glass doors, ambient lighting, and sauna benching.',
    icon: 'Flame',
    popularStyles: ['Nordic Cedar', 'Modern Glass Sauna', 'Japanese Hinoki'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'man-cave',
    name: 'Man Cave',
    category: 'interior',
    description: 'Ultimate retreat rooms with sports bars, pool tables, plush sectional seating, and ambient lighting.',
    icon: 'Tv',
    popularStyles: ['Industrial Brick', 'Dark Leather Luxury', 'Sports Lounge'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'foyer',
    name: 'Foyer',
    category: 'interior',
    description: 'Grand entryways with statement light fixtures, console tables, decorative mirrors, and tiled entry flooring.',
    icon: 'DoorOpen',
    popularStyles: ['Classic Grandeur', 'Modern Minimalist Entry', 'Warm Welcoming'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'prayer-room',
    name: 'Prayer room',
    category: 'interior',
    description: 'Serene, peaceful spiritual prayer and meditation spaces with soft rugs, warm lighting, and minimal distraction.',
    icon: 'HeartHandshake',
    popularStyles: ['Tranquil Zen', 'Traditional Sacred', 'Minimalist Warmth'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'wine-cellar',
    name: 'Wine Cellar',
    category: 'interior',
    description: 'Climate-controlled wine rooms featuring custom wooden racks, stone accents, glass doors, and ambient lighting.',
    icon: 'Wine',
    popularStyles: ['Rustic Stone & Oak', 'Modern Glass Vault', 'Luxury Underground'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'sunroom',
    name: 'Sunroom',
    category: 'interior',
    description: 'Glass-enclosed sunrooms filled with natural sunlight, indoor greenery, wicker furniture, and garden views.',
    icon: 'Sun',
    popularStyles: ['Botanical Conservatory', 'Coastal White', 'Scandinavian Glass'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'home-spa',
    name: 'Home Spa',
    category: 'interior',
    description: 'Wellness retreats featuring jacuzzi tubs, steam showers, teak accents, stone walls, and soothing aromatherapy ambient lighting.',
    icon: 'Sparkles',
    popularStyles: ['Zen Sanctuary', 'Luxury Marble Spa', 'Balinese Teak'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'mudroom',
    name: 'Mudroom',
    category: 'interior',
    description: 'Transition entry spaces with coat hooks, shoe cubbies, bench seating, and durable tile flooring.',
    icon: 'Footprints',
    popularStyles: ['Modern Farmhouse', 'Clean Built-In', 'Rustic Entry'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'craft-room',
    name: 'Craft Room',
    category: 'interior',
    description: 'Creative maker rooms with modular workbenches, art supply racks, pegboards, and bright task lighting.',
    icon: 'Palette',
    popularStyles: ['Bright Organized Studio', 'Creative Pastel', 'Industrial Maker'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'dressing-room',
    name: 'Dressing Room',
    category: 'interior',
    description: 'Elegant personal dressing suites with lighted vanity mirrors, plush ottomans, and custom wardrobe displays.',
    icon: 'Scissors',
    popularStyles: ['Glamour Velvet', 'Minimalist Chic', 'Hollywood Mirrors'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'home-bar',
    name: 'Home Bar',
    category: 'interior',
    description: 'Sophisticated entertaining bars with stone counters, bar stools, glass shelving, and LED backlit liquor displays.',
    icon: 'GlassWater',
    popularStyles: ['Speakeasy Dark Wood', 'Modern Marble Bar', 'Industrial Brass'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'library',
    name: 'Library',
    category: 'interior',
    description: 'Classic floor-to-ceiling book havens with rolling ladders, leather armchairs, fireplace hearths, and warm desk lighting.',
    icon: 'Library',
    popularStyles: ['Classic Mahogany', 'Modern Minimalist Shelf', 'Dark Academia'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'art-studio',
    name: 'Art Studio',
    category: 'interior',
    description: 'Sun-drenched creative studio spaces with easel stations, paint storage racks, splash-resistant flooring, and skylights.',
    icon: 'Palette',
    popularStyles: ['Industrial Loft Studio', 'Boho Painter Nook', 'Bright White Gallery'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'yoga-studio',
    name: 'Yoga Studio',
    category: 'interior',
    description: 'Tranquil yoga and meditation rooms with bamboo flooring, full-length mirrors, soft ambient lighting, and indoor plants.',
    icon: 'Heart',
    popularStyles: ['Zen Bamboo', 'Minimalist Warm Wood', 'Sacred Sanctuary'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'photo-studio',
    name: 'Photo Studio',
    category: 'interior',
    description: 'Professional photo production environments with backdrop stands, softbox lights, reflector panels, and workstation desks.',
    icon: 'Camera',
    popularStyles: ['Minimalist Cyclorama', 'Industrial Studio', 'Modern Creative'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'multimedia-room',
    name: 'Multimedia Room',
    category: 'interior',
    description: 'Versatile media hubs equipped with surround sound, smart TV walls, gaming consoles, and modular lounge seating.',
    icon: 'Video',
    popularStyles: ['Cyberpunk Dark', 'Modern Tech Lounge', 'Minimalist Media'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'music-room',
    name: 'Music Room',
    category: 'interior',
    description: 'Acoustically tuned music sanctuaries with grand piano setups, guitar wall displays, amplifiers, and soundproof panels.',
    icon: 'Music',
    popularStyles: ['Acoustic Warm Wood', 'Vintage Rock Studio', 'Modern Classical'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'home-gym',
    name: 'Home Gym',
    category: 'interior',
    description: 'Personal workout sanctuaries featuring heavy-duty rubber flooring, dumbbell racks, power cages, and wall mirrors.',
    icon: 'Dumbbell',
    popularStyles: ['Industrial Gym', 'Modern Black & Oak', 'Minimalist Fitness'],
    compatibleToolSlugs: ['interior-design', 'ai-flooring-design'],
  },

  // --- Exterior Spaces ---
  {
    slug: 'balcony',
    name: 'Balcony',
    category: 'exterior',
    description: 'Urban outdoor balconies with rattan lounge chairs, potted plants, and wooden deck tiles.',
    icon: 'Sun',
    popularStyles: ['Boho Oasis', 'Modern Urban Garden', 'Minimalist Deck'],
    compatibleToolSlugs: ['landscape-design', 'exterior-design'],
  },
  {
    slug: 'outdoor-kitchen',
    name: 'Outdoor Kitchen',
    category: 'exterior',
    description: 'Al fresco cooking patios equipped with built-in stainless grills, stone counters, pizza ovens, and dining seating.',
    icon: 'Flame',
    popularStyles: ['Modern Stone Grill', 'Rustic Timber Patio', 'Luxury Resort Bar'],
    compatibleToolSlugs: ['landscape-design', 'exterior-design'],
  },
  {
    slug: 'greenhouse',
    name: 'Greenhouse',
    category: 'exterior',
    description: 'Glass botanical houses with potting benches, terracotta planters, vertical garden racks, and abundant sunshine.',
    icon: 'Flower2',
    popularStyles: ['Victorian Iron', 'Modern Black Frame', 'Rustic Garden Glass'],
    compatibleToolSlugs: ['landscape-design', 'exterior-design'],
  },
  {
    slug: 'she-shed',
    name: 'She Shed',
    category: 'exterior',
    description: 'Charming garden retreats styled for craft, reading, relaxation, or tea in cozy outdoor garden settings.',
    icon: 'Sparkles',
    popularStyles: ['Cottagecore', 'Bohemian Garden', 'Pastel Sanctuary'],
    compatibleToolSlugs: ['landscape-design', 'exterior-design'],
  },
  {
    slug: 'conservatory',
    name: 'Conservatory',
    category: 'exterior',
    description: 'Glass architectural garden rooms filled with exotic botanical displays, wrought iron seating, and natural sunlight.',
    icon: 'Sun',
    popularStyles: ['Classic Glass House', 'Modern English Garden', 'Luxury Sun Sanctuary'],
    compatibleToolSlugs: ['landscape-design', 'exterior-design'],
  },
  {
    slug: 'rooftop-terrace',
    name: 'Rooftop Terrace',
    category: 'exterior',
    description: 'Skyline rooftop lounges with fire pits, sectional outdoor sofas, wooden decking, and perimeter planters.',
    icon: 'Building',
    popularStyles: ['Modern Urban Resort', 'Penthouse Firepit', 'Minimalist View'],
    compatibleToolSlugs: ['landscape-design', 'exterior-design'],
  },

  // --- Commercial Spaces ---
  {
    slug: 'office',
    name: 'Office',
    category: 'commercial',
    description: 'Professional commercial office space with open plan workstations, glass partitions, and ergonomic furniture.',
    icon: 'Building',
    popularStyles: ['Corporate Minimalist', 'Modern Tech', 'Industrial Commercial'],
    compatibleToolSlugs: ['office-design', 'interior-design'],
  },
  {
    slug: 'working-space',
    name: 'Working Space',
    category: 'commercial',
    description: 'Flexible communal work hubs with desk hot-desking, phone booths, lounge seating, and high-speed lighting.',
    icon: 'Laptop',
    popularStyles: ['Flexible Urban', 'Modern Industrial', 'Biophilic Workspace'],
    compatibleToolSlugs: ['office-design', 'interior-design'],
  },
  {
    slug: 'coworking-space',
    name: 'Coworking space',
    category: 'commercial',
    description: 'Vibrant shared community workspaces featuring open desks, private booths, coffee bars, and breakout zones.',
    icon: 'Users',
    popularStyles: ['Vibrant Creative Loft', 'Modern Industrial', 'Scandinavian Hub'],
    compatibleToolSlugs: ['office-design', 'interior-design'],
  },
  {
    slug: 'meeting-room',
    name: 'Meeting room',
    category: 'commercial',
    description: 'Professional conference rooms with video-call screens, conference tables, and acoustic ceiling baffles.',
    icon: 'Monitor',
    popularStyles: ['Executive Corporate', 'Tech Startup Modern', 'Minimalist Glass'],
    compatibleToolSlugs: ['office-design', 'interior-design'],
  },
  {
    slug: 'workshop',
    name: 'Workshop',
    category: 'commercial',
    description: 'Functional craft and maker workshops with heavy-duty workbenches, pegboards, and industrial lighting.',
    icon: 'Wrench',
    popularStyles: ['Industrial Woodworking', 'Modern Garage Workshop', 'Craft Studio'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'fitness-gym',
    name: 'Fitness gym',
    category: 'commercial',
    description: 'Home & commercial gyms with rubber flooring, dumbbell racks, mirrors, and motivational wall art.',
    icon: 'Activity',
    popularStyles: ['Industrial Gym', 'Luxury Wellness Suite', 'Minimalist Home Gym'],
    compatibleToolSlugs: ['interior-design', 'ai-flooring-design'],
  },
  {
    slug: 'coffee-shop',
    name: 'Coffee shop',
    category: 'commercial',
    description: 'Cozy boutique coffee shops with espresso bars, warm wood seating, pendant lamps, and chalkboard menus.',
    icon: 'Coffee',
    popularStyles: ['Artisanal Industrial', 'Modern Minimalist Cafe', 'Rustic Warm Wood'],
    compatibleToolSlugs: ['interior-design', 'exterior-design'],
  },
  {
    slug: 'clothing-store',
    name: 'Clothing store',
    category: 'commercial',
    description: 'High-end retail boutiques with clothes racks, fitting rooms, display pedestals, and spotlighting.',
    icon: 'ShoppingBag',
    popularStyles: ['Luxury Minimalist Retail', 'Modern Industrial Boutique', 'Nordic Fashion'],
    compatibleToolSlugs: ['interior-design', 'change-room-light'],
  },
  {
    slug: 'restaurant',
    name: 'Restaurant',
    category: 'commercial',
    description: 'Atmospheric dining restaurants with booth seating, bar counter design, mood lighting, and accent entryways.',
    icon: 'UtensilsCrossed',
    popularStyles: ['Luxury Fine Dining', 'Modern Bistro', 'Industrial Gastropub'],
    compatibleToolSlugs: ['interior-design', 'exterior-design'],
  },
  {
    slug: 'science-laboratory',
    name: 'Science Laboratory',
    category: 'commercial',
    description: 'Clean research lab facilities equipped with chemical-resistant lab benches, fume hoods, and bright ceiling panels.',
    icon: 'FlaskConical',
    popularStyles: ['Modern Clinical White', 'High-Tech Research', 'Clean Minimalist'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'wedding-room',
    name: 'Wedding Room',
    category: 'commercial',
    description: 'Romantic bridal suites and wedding reception halls with floral arches, crystal chandeliers, and drapery.',
    icon: 'Heart',
    popularStyles: ['Romantic Luxury', 'Bohemian Floral', 'Classic Elegance'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'hotel-lobby',
    name: 'Hotel lobby',
    category: 'commercial',
    description: 'Grand hospitality lobbies with reception counters, luxury seating groups, statement lighting, and marble floors.',
    icon: 'Building2',
    popularStyles: ['Luxury Resort', 'Modern Boutique Hotel', 'Classic Opulence'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'hotel-room',
    name: 'Hotel room',
    category: 'commercial',
    description: 'Sophisticated hospitality guest rooms with king beds, desk nooks, accent lighting, and panoramic views.',
    icon: 'Hotel',
    popularStyles: ['5-Star Luxury Suite', 'Modern Boutique', 'Minimalist Comfort'],
    compatibleToolSlugs: ['bedroom-design', 'interior-design'],
  },
  {
    slug: 'hotel-bathroom',
    name: 'Hotel bathroom',
    category: 'commercial',
    description: 'Opulent hotel ensuites with freestanding soaking tubs, double marble vanities, rain showers, and backlit mirrors.',
    icon: 'Bath',
    popularStyles: ['Luxury Marble Spa', 'Modern Chrome & Tile', 'Minimalist Stone'],
    compatibleToolSlugs: ['bathroom-design', 'interior-design'],
  },
  {
    slug: 'exhibition-space',
    name: 'Exhibition space',
    category: 'commercial',
    description: 'Spacious art gallery and trade exhibition halls with moveable display walls, gallery track lighting, and polished concrete.',
    icon: 'Image',
    popularStyles: ['Contemporary White Cube', 'Industrial Art Gallery', 'Minimalist Display'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'onsen',
    name: 'Onsen',
    category: 'commercial',
    description: 'Traditional Japanese bathhouses featuring natural stone hot spring pools, bamboo screens, teak decking, and vapor ambient light.',
    icon: 'Droplets',
    popularStyles: ['Traditional Japanese Ryokan', 'Modern Stone Bath', 'Zen Mineral Spring'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'auditorium',
    name: 'Auditorium',
    category: 'commercial',
    description: 'Tiered performance halls with acoustic paneling, stage lighting, row seating, and grand presentation stages.',
    icon: 'Tv2',
    popularStyles: ['Modern Acoustic', 'Classic Theater', 'Tech Conference Hall'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'medical-exam-room',
    name: 'Medical Exam Room',
    category: 'commercial',
    description: 'Hygienic, comfortable healthcare treatment rooms with exam tables, cabinetry, sanitizer stations, and gentle lighting.',
    icon: 'Stethoscope',
    popularStyles: ['Modern Clinical Serenity', 'Soft Warm Medical', 'Minimalist Clean'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'reception-area',
    name: 'Reception Area',
    category: 'commercial',
    description: 'Welcoming corporate & clinic reception foyers with custom reception desks, brand wall backdrop, and waiting seating.',
    icon: 'ConciergeBell',
    popularStyles: ['Corporate Executive', 'Modern Minimalist Desk', 'Warm Hospitality'],
    compatibleToolSlugs: ['interior-design'],
  },
  {
    slug: 'music-room',
    name: 'Music Room',
    category: 'interior',
    description: 'Acoustically tuned music sanctuaries with grand piano setups, guitar wall displays, amplifiers, and soundproof panels.',
    icon: 'Music',
    popularStyles: ['Acoustic Warm Wood', 'Vintage Rock Studio', 'Modern Classical'],
    compatibleToolSlugs: ['interior-design'],
  },
];

@Injectable()
export class RoomTypesService implements OnModuleInit {
  private readonly logger = new Logger(RoomTypesService.name);

  constructor(
    @InjectModel(RoomType.name)
    private readonly roomTypeModel: Model<RoomTypeDocument>,
  ) {}

  /**
   * Automatically seed roomtypes collection in MongoDB Atlas on startup
   */
  async onModuleInit() {
    try {
      for (const roomType of SEED_ROOM_TYPES) {
        await this.roomTypeModel.updateOne(
          { slug: roomType.slug },
          { $set: roomType },
          { upsert: true },
        );
      }
      this.logger.log(`✅ Successfully seeded/synced 20 Room Types into MongoDB roomtypes collection!`);
    } catch (err) {
      this.logger.warn(`Could not seed roomtypes into MongoDB Atlas (${err.message})`);
    }
  }

  /**
   * Get all room types
   */
  async findAll(): Promise<RoomType[]> {
    try {
      const roomTypes = await this.roomTypeModel.find().exec();
      if (roomTypes && roomTypes.length > 0) return roomTypes;
    } catch (e) {
      // Fall through to memory dataset
    }
    return SEED_ROOM_TYPES as RoomType[];
  }

  /**
   * Get single room type by slug
   */
  async findBySlug(slug: string): Promise<RoomType> {
    try {
      const found = await this.roomTypeModel.findOne({ slug }).exec();
      if (found) return found;
    } catch (e) {
      // Fall through
    }
    return SEED_ROOM_TYPES.find((r) => r.slug === slug) as RoomType;
  }
}
