'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

const SHOWCASE_IMAGES = [
  { id: 'slide-1', url: '/samples/japandi_sunlit.png', alt: 'Sunlit Japandi Room' },
  { id: 'slide-2', url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&auto=format&fit=crop&q=80', alt: 'Modern Architectural Villa' },
  { id: 'slide-3', url: '/samples/japandi_living.png', alt: 'Classical Golden Hour Lounge' },
  { id: 'slide-4', url: '/samples/bedroom_after.png', alt: 'Minimalist Master Bedroom' },
  { id: 'slide-5', url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1000&auto=format&fit=crop&q=80', alt: 'Contemporary Modern Lounge' },
  { id: 'slide-6', url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=1000&auto=format&fit=crop&q=80', alt: 'Sunlit Outdoor Terrace' },
];

export default function RoomsShowcaseSection() {
  const [currentIndex, setCurrentIndex] = useState(0);

  // Every 5 seconds (5000ms), advance track index so images enter from right to center
  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentIndex((prev) => (prev + 1) % SHOWCASE_IMAGES.length);
    }, 5000);
    return () => clearInterval(timer);
  }, []);

  const leftIndex = currentIndex % SHOWCASE_IMAGES.length;
  const centerIndex = (currentIndex + 1) % SHOWCASE_IMAGES.length;
  const rightIndex = (currentIndex + 2) % SHOWCASE_IMAGES.length;

  return (
    <section className="relative w-full py-20 bg-[#2563eb]/10 dark:bg-[#2563eb]/20 border-y border-[#2563eb]/15 dark:border-[#2563eb]/30 text-slate-900 dark:text-white selection:bg-blue-600 selection:text-white overflow-hidden">
      <div className="max-w-7xl mx-auto px-6 sm:px-8 lg:px-10 space-y-12">

        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto space-y-3">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-3xl sm:text-5xl font-extrabold tracking-tight text-slate-900 dark:text-white font-heading"
          >
            Rooms that <span className="text-blue-600 dark:text-blue-400">RoomAI</span> created
          </motion.h2>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-sm sm:text-base text-slate-600 dark:text-slate-300 font-medium"
          >
            Explore photorealistic interior, exterior, and architectural spaces generated by RoomAI in seconds.
          </motion.p>
        </div>

        {/* 3-Card Carousel Track (Center Card enters smoothly from RIGHT to CENTER every 5s) */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-center">
          
          {/* Left Flank Card */}
          <div className="lg:col-span-3 hidden lg:block h-[340px] rounded-2xl overflow-hidden shadow-xl border border-white/80 bg-slate-900 relative">
            <AnimatePresence mode="popLayout">
              <motion.img
                key={SHOWCASE_IMAGES[leftIndex].id}
                src={SHOWCASE_IMAGES[leftIndex].url}
                alt={SHOWCASE_IMAGES[leftIndex].alt}
                initial={{ opacity: 0, x: 200 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -200 }}
                transition={{ duration: 1.4, ease: [0.16, 1, 0.3, 1] }}
                className="w-full h-full object-cover absolute inset-0"
              />
            </AnimatePresence>
          </div>

          {/* Center Main Spotlight Card (ENTERS SMOOTHLY FROM RIGHT TO CENTER EVERY 5 SECONDS) */}
          <div className="lg:col-span-6 relative h-[360px] sm:h-[450px] rounded-2xl overflow-hidden shadow-2xl border-2 border-blue-200/80 bg-slate-900">
            <AnimatePresence mode="popLayout">
              <motion.img
                key={SHOWCASE_IMAGES[centerIndex].id}
                src={SHOWCASE_IMAGES[centerIndex].url}
                alt={SHOWCASE_IMAGES[centerIndex].alt}
                initial={{ opacity: 0, x: 300, scale: 0.95 }}
                animate={{ opacity: 1, x: 0, scale: 1 }}
                exit={{ opacity: 0, x: -300, scale: 0.95 }}
                transition={{ duration: 1.4, ease: [0.16, 1, 0.3, 1] }}
                className="w-full h-full object-cover absolute inset-0"
              />
            </AnimatePresence>
          </div>

          {/* Right Flank Card */}
          <div className="lg:col-span-3 hidden lg:block h-[340px] rounded-2xl overflow-hidden shadow-xl border border-white/80 bg-slate-900 relative">
            <AnimatePresence mode="popLayout">
              <motion.img
                key={SHOWCASE_IMAGES[rightIndex].id}
                src={SHOWCASE_IMAGES[rightIndex].url}
                alt={SHOWCASE_IMAGES[rightIndex].alt}
                initial={{ opacity: 0, x: 200 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -200 }}
                transition={{ duration: 1.4, ease: [0.16, 1, 0.3, 1] }}
                className="w-full h-full object-cover absolute inset-0"
              />
            </AnimatePresence>
          </div>

        </div>

      </div>
    </section>
  );
}
