import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Product, ProductDocument } from './schemas/product.schema';

const SEED_PRODUCTS = [
  // ==========================================
  // 1. FURNITURE (15 items)
  // ==========================================
  {
    slug: 'sectional-l-shape-sofa',
    name: 'Sectional L-Shape Fabric Sofa',
    type: 'furniture',
    roomTypes: ['living-room', 'family-room', 'lounge', 'home-theater', 'open-kitchen-living', 'sunroom'],
    description: 'Deep cushioned plush sectional sofa in warm cream linen upholstery.',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'executive-walnut-desk',
    name: 'Executive Walnut Office Desk',
    type: 'furniture',
    roomTypes: ['home-office', 'study-room', 'office', 'working-space', 'library'],
    description: 'Solid walnut executive desk with integrated cable management and brass drawer pulls.',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'velvet-king-bed',
    name: 'Velvet Upholstered King Bed Frame',
    type: 'furniture',
    roomTypes: ['bedroom', 'guest-bedroom', 'hotel-room', 'master-bedroom', 'nursery'],
    description: 'Plush tufted velvet headboard in serene emerald green with matte gold legs.',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },
  {
    slug: 'solid-oak-dining-table',
    name: 'Solid Oak 8-Seater Dining Table',
    type: 'furniture',
    roomTypes: ['dining-room', 'formal-dining', 'open-kitchen-living', 'restaurant'],
    description: 'Handcrafted light oak dining table with soft rounded edges.',
    image: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'cognac-leather-armchair',
    name: 'Cognac Leather Lounge Armchair',
    type: 'furniture',
    roomTypes: ['living-room', 'reading-nook', 'home-office', 'foyer', 'lounge', 'man-cave'],
    description: 'Mid-century icon arm chair upholstered in top-grain cognac leather.',
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'leather-recliner-chair',
    name: 'Power Recliner Leather Chair',
    type: 'furniture',
    roomTypes: ['living-room', 'home-theater', 'man-cave', 'lounge'],
    description: 'Electric power recliner with USB charging port and memory foam lumbar support.',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'floating-tv-media-unit',
    name: 'Floating Wooden TV Console & Wall Unit',
    type: 'furniture',
    roomTypes: ['living-room', 'bedroom', 'family-room', 'home-theater'],
    description: 'Sleek wall-mounted media console with slatted wood doors and concealed cable management.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'oak-bookshelf-cabinet',
    name: 'Tall Oak Bookshelf & Glass Display Cabinet',
    type: 'furniture',
    roomTypes: ['study-room', 'home-office', 'library', 'living-room'],
    description: '5-tier oak wood bookcase with tempered glass display doors and LED downlighting.',
    image: 'https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: false,
  },
  {
    slug: 'vanity-dressing-table',
    name: 'Vanity Dressing Table with Illuminated Mirror',
    type: 'furniture',
    roomTypes: ['bedroom', 'dressing-room', 'walk-in-closet'],
    description: 'White marble-top dressing table with soft LED halo ring mirror and velvet stool.',
    image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'nesting-marble-side-tables',
    name: 'Nesting Brass & Marble Side Tables (Set of 2)',
    type: 'furniture',
    roomTypes: ['living-room', 'lounge', 'bedroom', 'foyer'],
    description: 'Pair of round white marble nesting accent end tables with brushed brass metal legs.',
    image: 'https://images.unsplash.com/photo-1532323544230-7191fd51bc1b?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: false,
  },
  {
    slug: 'kitchen-island-barstools',
    name: 'Leather & Steel Bar Stools (Set of 3)',
    type: 'furniture',
    roomTypes: ['kitchen', 'open-kitchen-living', 'home-bar', 'coffee-shop'],
    description: 'Ergonomic counter height bar stools with distressed brown leather seat and black steel frame.',
    image: 'https://images.unsplash.com/photo-1503602642458-232111445657?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'bunk-bed-kids-storage',
    name: 'Solid Wood Kids Bunk Bed with Storage Stairs',
    type: 'furniture',
    roomTypes: ['kids-room', 'nursery', 'playroom'],
    description: 'Modular timber bunk bed featuring built-in bookshelf stairs and underbed storage drawers.',
    image: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: false,
  },
  {
    slug: 'teak-outdoor-lounge-set',
    name: 'Teak Wood Outdoor Patio Lounge Sofa Set',
    type: 'furniture',
    roomTypes: ['balcony', 'outdoor-kitchen', 'patio-decking', 'rooftop-terrace', 'sunroom'],
    description: 'Weather-resistant teak lounge set with water-repellent beige cushions.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'custom-walk-in-wardrobe-system',
    name: 'Modular Custom Walk-in Wardrobe System',
    type: 'furniture',
    roomTypes: ['walk-in-closet', 'dressing-room', 'bedroom'],
    description: 'Floor-to-ceiling illuminated organizer with shoe racks, tie drawers, and glass display cases.',
    image: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },
  {
    slug: 'wine-display-racks-oak',
    name: 'Oak & Steel Modular Wine Rack System',
    type: 'furniture',
    roomTypes: ['wine-cellar', 'home-bar', 'dining-room'],
    description: 'Temperature-suitable solid oak wine shelving grid with LED accent backlighting.',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: false,
  },

  // ==========================================
  // 2. ELECTRONICS & COOLING / FANS (10 items)
  // ==========================================
  {
    slug: 'ceiling-electric-fan',
    name: 'Modern Smart Ceiling Electric Fan with Light',
    type: 'electronics',
    roomTypes: ['living-room', 'bedroom', 'dining-room', 'kitchen', 'home-office', 'sunroom', 'balcony'],
    description: 'Ultra-quiet DC motor smart ceiling fan with dimmable LED ring light and remote control.',
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'split-air-conditioner',
    name: 'Inverter Split Air Conditioner (AC)',
    type: 'electronics',
    roomTypes: ['living-room', 'bedroom', 'guest-bedroom', 'home-office', 'hotel-room', 'gaming-room'],
    description: 'Sleek matte white wall-mounted inverter split AC with ultra-quiet cooling and PM2.5 air filter.',
    image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'retro-table-fan',
    name: 'Retro Metal Oscillating Table Fan',
    type: 'electronics',
    roomTypes: ['bedroom', 'home-office', 'study-room', 'reading-nook', 'coffee-shop'],
    description: 'Vintage brushed copper oscillating desk fan with 3 speed quiet airflow.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: true,
  },
  {
    slug: 'tower-air-cooler',
    name: 'Oscillating Tower Fan & HEPA Air Purifier',
    type: 'electronics',
    roomTypes: ['living-room', 'bedroom', 'fitness-gym', 'sunroom'],
    description: 'Bladeless quiet tower fan with built-in HEPA filtration and ambient room temperature sensor.',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: false,
  },
  {
    slug: 'smart-4k-oled-tv',
    name: '65-Inch Smart 4K OLED Ultra HD TV',
    type: 'electronics',
    roomTypes: ['living-room', 'bedroom', 'home-theater', 'man-cave', 'lounge'],
    description: 'Ultra-thin bezel smart 4K OLED TV with cinematic HDR and built-in voice assistant.',
    image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },
  {
    slug: 'dolby-atmos-soundbar',
    name: 'Wireless Dolby Atmos Soundbar System',
    type: 'electronics',
    roomTypes: ['living-room', 'home-theater', 'gaming-room', 'multimedia-room'],
    description: 'Surround sound audio bar with wireless subwoofer and Bluetooth streaming.',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'smart-air-purifier',
    name: 'Smart HEPA Air Purifier with PM2.5 Sensor',
    type: 'electronics',
    roomTypes: ['bedroom', 'nursery', 'living-room', 'home-office'],
    description: 'Whisper-quiet air purifier removing allergens, odors, and airborne dust particles.',
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: false,
  },
  {
    slug: 'ceramic-electric-heater',
    name: 'PTC Ceramic Oscillating Tower Space Heater',
    type: 'electronics',
    roomTypes: ['bedroom', 'bathroom', 'home-office', 'study-room'],
    description: 'Fast ambient heating tower space heater with digital thermostat and tip-over safety switch.',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
  {
    slug: '4k-laser-cinema-projector',
    name: 'Ultra Short Throw 4K Laser Cinema Projector',
    type: 'electronics',
    roomTypes: ['home-theater', 'living-room', 'multimedia-room'],
    description: 'Project crisp 120-inch 4K HDR images from just inches away from the wall.',
    image: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },
  {
    slug: 'robot-vacuum-cleaner',
    name: 'Smart LiDAR Robot Vacuum & Mop Combo',
    type: 'electronics',
    roomTypes: ['living-room', 'kitchen', 'hallway', 'bedroom'],
    description: 'Autonomous laser-navigating robot vacuum with self-emptying base station.',
    image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },

  // ==========================================
  // 3. DECORATION (10 items)
  // ==========================================
  {
    slug: 'ceramic-terracotta-vases',
    name: 'Artisanal Terracotta Ceramic Vase Set',
    type: 'decoration',
    roomTypes: ['living-room', 'dining-room', 'foyer', 'sunroom', 'coffee-shop', 'hotel-lobby'],
    description: 'Hand-thrown matte clay terracotta vases with natural dried pampas grass.',
    image: 'https://images.unsplash.com/photo-1612196808214-b7e239e5f6b7?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
  {
    slug: 'abstract-canvas-wall-art',
    name: 'Oversized Abstract Canvas Wall Art',
    type: 'decoration',
    roomTypes: ['living-room', 'bedroom', 'home-office', 'foyer', 'hotel-lobby', 'conference-room'],
    description: 'Textured gallery-wrapped canvas with warm beige, black, and metallic gold brushstrokes.',
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'organic-arch-mirror',
    name: 'Full-Length Brass Arch Mirror',
    type: 'decoration',
    roomTypes: ['bedroom', 'dressing-room', 'walk-in-closet', 'foyer', 'bathroom', 'hotel-room'],
    description: 'Minimalist curved arch floor mirror with ultra-thin brushed brass aluminum border.',
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'bohemian-woven-area-rug',
    name: 'Hand-Knotted Wool Berber Area Rug (8x10)',
    type: 'decoration',
    roomTypes: ['living-room', 'bedroom', 'nursery', 'sunroom', 'lounge'],
    description: 'Soft high-pile wool area rug with traditional Moroccan tribal diamond patterns.',
    image: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'minimalist-ceramic-sculpture',
    name: 'Minimalist Ceramic Tabletop Sculpture',
    type: 'decoration',
    roomTypes: ['living-room', 'home-office', 'study-room', 'reception-area'],
    description: 'Abstract organic clay sculpture in matte white glaze.',
    image: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
  {
    slug: 'vintage-wall-clock',
    name: 'Minimalist Large Metal Wall Clock',
    type: 'decoration',
    roomTypes: ['kitchen', 'living-room', 'dining-room', 'office'],
    description: 'Silent sweep non-ticking oversized black metal wall clock with gold hands.',
    image: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
  {
    slug: 'silk-drapery-curtains',
    name: 'Floor-Length Linen Silk Drapery Curtains',
    type: 'decoration',
    roomTypes: ['living-room', 'bedroom', 'dining-room', 'sunroom'],
    description: 'Light filtering cream linen curtains with blackout privacy lining.',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'decorative-throw-cushions',
    name: 'Bouclé & Velvet Decorative Throw Pillows (Set of 4)',
    type: 'decoration',
    roomTypes: ['living-room', 'bedroom', 'reading-nook', 'lounge'],
    description: 'Textured bouclé and plush velvet accent cushions in warm neutral earth tones.',
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: true,
  },
  {
    slug: 'fluted-wood-wall-panels',
    name: 'Acoustic Fluted Wooden Wall Paneling',
    type: 'decoration',
    roomTypes: ['living-room', 'bedroom', 'home-office', 'home-theater'],
    description: '3D slatted oak accent wall panels providing acoustic sound dampening.',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'woven-macrame-tapestry',
    name: 'Handwoven Cotton Macrame Wall Hanging',
    type: 'decoration',
    roomTypes: ['bedroom', 'bohemian-room', 'nursery', 'sunroom'],
    description: 'Boho braided cotton yarn wall hanging suspended on natural driftwood branch.',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },

  // ==========================================
  // 4. LIGHTING (10 items)
  // ==========================================
  {
    slug: 'nordic-arc-floor-lamp',
    name: 'Nordic Arc Standing Floor Lamp',
    type: 'lighting',
    roomTypes: ['living-room', 'reading-nook', 'home-office', 'lounge', 'study-room'],
    description: 'Overhanging matte black arc lamp with warm dimmable LED glow shade.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'modern-brass-chandelier',
    name: 'Sputnik Brass Ring Chandelier',
    type: 'lighting',
    roomTypes: ['dining-room', 'formal-dining', 'foyer', 'hotel-lobby', 'kitchen', 'restaurant'],
    description: 'Sculptural brass pendant ring chandelier with frosted globe diffuser bulbs.',
    image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },
  {
    slug: 'smart-ambient-cove-strip-lighting',
    name: 'Recessed Architectural LED Cove Light Strip',
    type: 'lighting',
    roomTypes: ['bedroom', 'home-theater', 'bathroom', 'gaming-room', 'sauna', 'home-spa'],
    description: 'Tunable warm-to-cool RGBW smart LED ceiling cove lighting strip system.',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: true,
  },
  {
    slug: 'bedside-smoked-glass-lamp',
    name: 'Smoked Glass & Brass Bedside Lamp',
    type: 'lighting',
    roomTypes: ['bedroom', 'guest-bedroom', 'hotel-room', 'reading-nook'],
    description: 'Handblown smoked amber glass table lamp emitting soothing warm light.',
    image: 'https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
  {
    slug: 'edison-wall-sconce',
    name: 'Vintage Industrial Edison Bulb Wall Sconce',
    type: 'lighting',
    roomTypes: ['hallway', 'foyer', 'bathroom', 'man-cave', 'coffee-shop'],
    description: 'Matte black pipe fittings with exposed warm amber filament Edison bulb.',
    image: 'https://images.unsplash.com/photo-1550684848-bac1c5b4e853?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
  {
    slug: 'track-spotlight-system',
    name: 'Matte Black Ceiling Track Spotlight Bar',
    type: 'lighting',
    roomTypes: ['kitchen', 'art-gallery', 'home-office', 'living-room'],
    description: 'Adjustable 4-head directional track spotlights highlighting key artwork.',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'rattan-pendant-light',
    name: 'Handwoven Rattan Dome Pendant Light',
    type: 'lighting',
    roomTypes: ['dining-room', 'sunroom', 'kitchen', 'balcony', 'bohemian-room'],
    description: 'Organic natural wicker rattan shade casting warm geometric shadow patterns.',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'crystal-waterdrop-chandelier',
    name: 'Grand Crystal Waterdrop Rain Chandelier',
    type: 'lighting',
    roomTypes: ['foyer', 'hotel-lobby', 'formal-dining', 'ballroom'],
    description: 'Tiered glass crystal teardrop chandelier reflecting brilliant refracted light.',
    image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },
  {
    slug: 'minimalist-led-desk-lamp',
    name: 'Architectural Slim LED Desk Task Lamp',
    type: 'lighting',
    roomTypes: ['home-office', 'study-room', 'office', 'working-space'],
    description: 'Touch-controlled aluminum bar desk light with adjustable color temp and wireless phone charger.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: false,
  },
  {
    slug: 'outdoor-solar-garden-lantern',
    name: 'Warm LED Waterproof Outdoor Garden Lantern',
    type: 'lighting',
    roomTypes: ['balcony', 'patio-decking', 'rooftop-terrace', 'outdoor-kitchen'],
    description: 'Solar powered flickering flame lantern in durable weatherproof bronze metal housing.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },

  // ==========================================
  // 5. FLOORING (10 items)
  // ==========================================
  {
    slug: 'herringbone-oak-flooring',
    name: 'Herringbone European Light Oak Hardwood',
    type: 'flooring',
    roomTypes: ['living-room', 'bedroom', 'dining-room', 'home-office', 'foyer', 'walk-in-closet'],
    description: 'Classic herringbone pattern engineered oak with warm satin matte finish.',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'calacatta-marble-tile',
    name: 'Calacatta Gold Polished Marble Tile',
    type: 'flooring',
    roomTypes: ['bathroom', 'kitchen', 'foyer', 'hotel-bathroom', 'home-spa', 'sauna'],
    description: 'Large format white porcelain tile featuring dramatic grey and gold marble veining.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },
  {
    slug: 'slate-stone-tiles',
    name: 'Charcoal Matte Slate Stone Flooring',
    type: 'flooring',
    roomTypes: ['outdoor-kitchen', 'patio-decking', 'balcony', 'mudroom', 'laundry-room'],
    description: 'Durable non-slip natural slate tiles suitable for high-traffic and wet areas.',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: false,
  },
  {
    slug: 'polished-concrete-floor',
    name: 'Seamless Industrial Polished Concrete Floor',
    type: 'flooring',
    roomTypes: ['living-room', 'kitchen', 'home-gym', 'loft', 'garage'],
    description: 'High-gloss sealed concrete floor with subtle speckled aggregate texture.',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'dark-walnut-parquet-flooring',
    name: 'Dark American Walnut Parquet Hardwood',
    type: 'flooring',
    roomTypes: ['dining-room', 'library', 'master-bedroom', 'study-room'],
    description: 'Rich dark walnut chevron pattern wood flooring with deep grain character.',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },
  {
    slug: 'travertine-stone-tiles',
    name: 'Honed Ivory Travertine Natural Stone Tile',
    type: 'flooring',
    roomTypes: ['sunroom', 'patio-decking', 'bathroom', 'kitchen', 'foyer'],
    description: 'Warm beige honed travertine tile with organic pitted stone texture.',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: false,
  },
  {
    slug: 'terrazzo-mosaic-tile',
    name: 'Modern White & Pastel Terrazzo Tile',
    type: 'flooring',
    roomTypes: ['bathroom', 'kitchen', 'coffee-shop', 'entryway', 'laundry-room'],
    description: 'Playful composite terrazzo flooring infused with marble chips.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'plush-wool-carpet',
    name: 'Wall-to-Wall Plush Cream Wool Carpet',
    type: 'flooring',
    roomTypes: ['bedroom', 'nursery', 'home-theater', 'hotel-room'],
    description: 'Ultra-soft deep pile 100% natural wool carpeting for supreme foot comfort.',
    image: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: false,
  },
  {
    slug: 'bamboo-wood-flooring',
    name: 'Carbonized Strand Woven Bamboo Plank',
    type: 'flooring',
    roomTypes: ['sunroom', 'home-office', 'yoga-studio', 'bedroom'],
    description: 'Eco-friendly ultra-durable carbonized bamboo flooring in golden amber tone.',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: false,
  },
  {
    slug: 'hexagon-porcelain-tiles',
    name: 'Matte Black Hexagon Ceramic Floor Tile',
    type: 'flooring',
    roomTypes: ['bathroom', 'powder-room', 'mudroom', 'kitchen-backsplash'],
    description: 'Contemporary geometric honeycomb hex tile with crisp white grout lines.',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: true,
  },

  // ==========================================
  // 6. APPLIANCES & EQUIPMENT (10 items)
  // ==========================================
  {
    slug: 'french-door-smart-fridge',
    name: 'Counter-Depth Stainless Smart French Door Refrigerator',
    type: 'appliances',
    roomTypes: ['kitchen', 'open-kitchen-living', 'outdoor-kitchen'],
    description: 'Energy-star smart refrigerator with touch display and filtered ice dispenser.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },
  {
    slug: 'curved-oled-gaming-monitor',
    name: '49-Inch Curved OLED Ultra-Wide Monitor',
    type: 'appliances',
    roomTypes: ['gaming-room', 'home-office', 'multimedia-room', 'study-room'],
    description: 'High-refresh 240Hz curved OLED display for immersive work and gaming setups.',
    image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'commercial-espresso-machine',
    name: 'Dual Boiler Stainless Steel Espresso Machine',
    type: 'appliances',
    roomTypes: ['kitchen', 'home-bar', 'coffee-shop', 'office'],
    description: 'Professional grade home espresso machine with steam wand and PID temperature control.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'commercial-treadmill-gym',
    name: 'Foldable Smart Interactive Treadmill',
    type: 'appliances',
    roomTypes: ['home-gym', 'fitness-gym'],
    description: 'Heavy duty fitness treadmill with live streaming workout touchscreen screen.',
    image: 'https://images.unsplash.com/photo-1576678927484-cc909957088c?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: false,
  },
  {
    slug: 'built-in-quiet-dishwasher',
    name: 'Integrated Stainless Steel Built-In Dishwasher',
    type: 'appliances',
    roomTypes: ['kitchen', 'open-kitchen-living'],
    description: 'Ultra-silent 38dB dishwasher with 3rd rack utility tray and steam sanitize cycle.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'induction-glass-cooktop',
    name: '36-Inch Black Induction Glass Cooktop',
    type: 'appliances',
    roomTypes: ['kitchen', 'island-kitchen', 'outdoor-kitchen'],
    description: 'Rapid heating touch-control induction stove with flex-zone burner elements.',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'front-load-washer-dryer-combo',
    name: 'Smart Front-Load Stackable Washer Dryer Tower',
    type: 'appliances',
    roomTypes: ['laundry-room', 'mudroom', 'utility-closet'],
    description: 'High efficiency steam washing machine and heat pump dryer stack.',
    image: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: false,
  },
  {
    slug: 'dual-zone-wine-cooler',
    name: 'Under-Counter Dual Zone Wine Refrigerator',
    type: 'appliances',
    roomTypes: ['home-bar', 'kitchen', 'dining-room', 'wine-cellar'],
    description: '50-bottle capacity wine cooler with UV-protected glass door and wooden shelves.',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'countertop-air-fryer-oven',
    name: 'Smart Convection Countertop Air Fryer Oven',
    type: 'appliances',
    roomTypes: ['kitchen', 'dorm-room'],
    description: 'Multi-function stainless steel countertop oven with 10 preset cooking functions.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
  {
    slug: 'stainless-range-hood',
    name: 'Wall-Mounted Stainless Steel Kitchen Range Hood',
    type: 'appliances',
    roomTypes: ['kitchen', 'outdoor-kitchen'],
    description: 'High-CFM commercial grade kitchen ventilation hood with baffle filters and LED lights.',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: false,
  },

  // ==========================================
  // 7. FIXTURES & SANITARY (10 items)
  // ==========================================
  {
    slug: 'freestanding-soaking-tub',
    name: 'Acrylic Oval Freestanding Soaking Bathtub',
    type: 'fixtures',
    roomTypes: ['bathroom', 'home-spa', 'hotel-bathroom', 'master-bedroom'],
    description: 'Deep ergonomic white acrylic bathtub with floor-mounted brass filler tap.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },
  {
    slug: 'rainfall-shower-system-black',
    name: 'Matte Black Thermostatic Rainfall Showerhead System',
    type: 'fixtures',
    roomTypes: ['bathroom', 'home-spa', 'sauna', 'hotel-bathroom'],
    description: 'Ceiling mounted 12-inch rain shower head with body jets and hand sprayer.',
    image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'cedar-wood-sauna-room',
    name: 'Canadian Red Cedar Finnish Sauna Cabin',
    type: 'fixtures',
    roomTypes: ['sauna', 'home-spa'],
    description: 'Aromatic red cedar wood sauna unit with harvia heater and tempered glass door.',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: false,
  },
  {
    slug: 'brushed-brass-vanity-faucet',
    name: 'Brushed Brass Single-Hole Bathroom Vanity Faucet',
    type: 'fixtures',
    roomTypes: ['bathroom', 'powder-room'],
    description: 'Contemporary tall goose-neck brass faucet with ceramic disc cartridge.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: true,
  },
  {
    slug: 'double-vessel-sink-vanity',
    name: 'Floating Double Vessel Sink Bathroom Vanity',
    type: 'fixtures',
    roomTypes: ['bathroom', 'master-bathroom'],
    description: 'Wall-mounted oak vanity with dual white ceramic vessel sinks and soft-close drawers.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: true,
  },
  {
    slug: 'wall-hung-toilet',
    name: 'Matte White Wall-Hung Smart Toilet Bidet',
    type: 'fixtures',
    roomTypes: ['bathroom', 'powder-room'],
    description: 'Rimless elongated floating toilet with heated seat and warm air dryer.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Premium',
    isPopular: false,
  },
  {
    slug: 'stone-fireplace-hearth',
    name: 'Natural Stacked Stone Fireplace Hearth',
    type: 'fixtures',
    roomTypes: ['living-room', 'family-room', 'patio-decking', 'sunroom'],
    description: 'Rustic stacked stone fireplace surround with solid timber mantel shelf.',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },
  {
    slug: 'apron-sink-kitchen',
    name: 'White Fireclay Farmhouse Apron Front Kitchen Sink',
    type: 'fixtures',
    roomTypes: ['kitchen', 'laundry-room'],
    description: 'Heavy duty ceramic fireclay deep basin apron sink resistant to scratches and stains.',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'towel-warmer-rack',
    name: 'Wall-Mounted Stainless Electric Towel Warmer Rack',
    type: 'fixtures',
    roomTypes: ['bathroom', 'home-spa'],
    description: '10-bar heated towel rack with built-in timer for warm fluffy bath towels.',
    image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
  {
    slug: 'jacuzzi-hydro-tub',
    name: 'Whirlpool Hydrotherapy Jacuzzi Spa Tub',
    type: 'fixtures',
    roomTypes: ['home-spa', 'bathroom', 'patio-decking', 'hotel-suite'],
    description: 'Multi-jet hydrotherapy tub with chromotherapy underwater LED lighting.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Luxury',
    isPopular: true,
  },

  // ==========================================
  // 8. PLANTS & BOTANICALS (10 items)
  // ==========================================
  {
    slug: 'fiddle-leaf-fig-plant',
    name: 'Potted Fiddle Leaf Fig Tree',
    type: 'plant',
    roomTypes: ['living-room', 'sunroom', 'home-office', 'balcony', 'reception-area', 'hotel-lobby'],
    description: '6-foot live indoor leafy green tree in white fluted ceramic pot.',
    image: 'https://images.unsplash.com/photo-1545241047-6083a3684587?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: true,
  },
  {
    slug: 'monstera-deliciosa-pot',
    name: 'Lush Monstera Deliciosa Plant in Terracotta Pot',
    type: 'plant',
    roomTypes: ['living-room', 'bedroom', 'sunroom', 'coffee-shop', 'balcony'],
    description: 'Vibrant tropical Swiss cheese plant with split green leaves.',
    image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: true,
  },
  {
    slug: 'snake-plant-sansevieria',
    name: 'Snake Plant (Sansevieria Trifasciata) in Matte Black Pot',
    type: 'plant',
    roomTypes: ['bedroom', 'home-office', 'bathroom', 'living-room', 'hallway'],
    description: 'Hardy air-purifying upright yellow-edged snake plant.',
    image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: true,
  },
  {
    slug: 'olive-tree-terracotta',
    name: 'Potted Mediterranean Olive Tree',
    type: 'plant',
    roomTypes: ['living-room', 'dining-room', 'sunroom', 'patio-decking', 'foyer'],
    description: 'Slender silvery-green olive tree in rustic weathered clay terracotta planter.',
    image: 'https://images.unsplash.com/photo-1545241047-6083a3684587?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'bird-of-paradise-plant',
    name: 'Giant Strelitzia Bird of Paradise Floor Plant',
    type: 'plant',
    roomTypes: ['living-room', 'foyer', 'sunroom', 'hotel-lobby', 'balcony'],
    description: 'Dramatic broad-leaf tropical plant adding lush green height to open space.',
    image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: true,
  },
  {
    slug: 'golden-pothos-hanging-basket',
    name: 'Trailing Golden Pothos Vine in Hanging Ceramic Planter',
    type: 'plant',
    roomTypes: ['kitchen', 'bathroom', 'sunroom', 'bookshelf', 'balcony'],
    description: 'Cascading vine foliage with variegated green and yellow heart-shaped leaves.',
    image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
  {
    slug: 'japanese-zen-bonsai-tree',
    name: 'Japanese Zen Ficus Bonsai Tree in Shallow Ceramic Tray',
    type: 'plant',
    roomTypes: ['study-room', 'home-office', 'tea-room', 'living-room'],
    description: 'Sculpted mini bonsai tree with thick gnarled trunk and manicured green canopy.',
    image: 'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Medium',
    isPopular: false,
  },
  {
    slug: 'areca-feather-palm',
    name: 'Potted Areca Feather Palm Tree',
    type: 'plant',
    roomTypes: ['living-room', 'sunroom', 'office', 'reception-area'],
    description: 'Feathery arched tropical palm fronds bringing natural indoor brightness.',
    image: 'https://images.unsplash.com/photo-1545241047-6083a3684587?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
  {
    slug: 'peace-lily-plant',
    name: 'Blooming White Peace Lily (Spathiphyllum) in White Pot',
    type: 'plant',
    roomTypes: ['bedroom', 'bathroom', 'home-office', 'nursery'],
    description: 'Elegant dark green leaves with graceful white flower spathes.',
    image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
  {
    slug: 'hanging-succulent-terrarium',
    name: 'Glass Globe Hanging Succulent Terrarium',
    type: 'plant',
    roomTypes: ['window-nook', 'sunroom', 'kitchen', 'bedroom'],
    description: 'Geometric glass terrarium filled with mini echeveria succulents and white pebbles.',
    image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?q=80&w=800&auto=format&fit=crop',
    priceRange: 'Low',
    isPopular: false,
  },
];

@Injectable()
export class ProductsService implements OnModuleInit {
  private readonly logger = new Logger(ProductsService.name);

  constructor(
    @InjectModel(Product.name)
    private readonly productModel: Model<ProductDocument>,
  ) {}

  async onModuleInit() {
    try {
      for (const prod of SEED_PRODUCTS) {
        await this.productModel.updateOne(
          { slug: prod.slug },
          { $set: prod },
          { upsert: true },
        );
      }
      this.logger.log(`✅ Successfully seeded/synced ${SEED_PRODUCTS.length} Products into MongoDB products collection!`);
    } catch (err) {
      this.logger.warn(`Could not seed products into MongoDB Atlas (${err.message})`);
    }
  }

  async findAll(roomType?: string, type?: string): Promise<Product[]> {
    try {
      const query: any = {};
      if (roomType) query.roomTypes = roomType;
      if (type) query.type = type;

      const items = await this.productModel.find(query).exec();
      if (items && items.length > 0) return items;
    } catch (e) {
      // Fall through
    }
    return SEED_PRODUCTS.filter((p) => {
      if (roomType && !p.roomTypes.includes(roomType)) return false;
      if (type && p.type !== type) return false;
      return true;
    }) as Product[];
  }

  async findBySlug(slug: string): Promise<Product> {
    try {
      const found = await this.productModel.findOne({ slug }).exec();
      if (found) return found;
    } catch (e) {
      // Fall through
    }
    return SEED_PRODUCTS.find((p) => p.slug === slug) as Product;
  }
}
