/**
 * Application Constants Barrel Export
 */
export const APP_NAME = 'RoomAI';
export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api/v1';

export const DESIGN_STYLES = [
  { id: 'modern', name: 'Modern', description: 'Clean lines & neutral elegance', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=800&auto=format&fit=crop' },
  { id: 'minimalist', name: 'Minimalist', description: 'Clutter-free & essential layout', image: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=800&auto=format&fit=crop' },
  { id: 'industrial', name: 'Industrial', description: 'Exposed brick & dark steel', image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop' },
  { id: 'traditional', name: 'Traditional', description: 'Classic molding & rich mahogany', image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800&auto=format&fit=crop' },
  { id: 'scandinavian', name: 'Scandinavian', description: 'Bright, airy & light oak wood', image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop' },
  { id: 'japandi', name: 'Japandi', description: 'Wabi-sabi warm minimalism', image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=800&auto=format&fit=crop' },
  { id: 'luxury', name: 'Luxury', description: 'High-end marble & gold accents', image: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?q=80&w=800&auto=format&fit=crop' },
  { id: 'rustic', name: 'Rustic', description: 'Raw timber beams & stone hearth', image: 'https://images.unsplash.com/photo-1540518614846-7ede433c5163?q=80&w=800&auto=format&fit=crop' },
  { id: 'bohemian', name: 'Bohemian', description: 'Woven tapestries & indoor plants', image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=800&auto=format&fit=crop' },
  { id: 'classic', name: 'Classic', description: 'Timeless proportioned furnishings', image: 'https://images.unsplash.com/photo-1616137466211-f939a420be84?q=80&w=800&auto=format&fit=crop' },
  { id: 'contemporary', name: 'Contemporary', description: 'State-of-the-art lighting & curved sofas', image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=800&auto=format&fit=crop' },
  { id: 'mediterranean', name: 'Mediterranean', description: 'Terracotta tile & whitewashed stucco', image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop' },
  { id: 'farmhouse', name: 'Farmhouse', description: 'Apron sinks & shiplap accent walls', image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=800&auto=format&fit=crop' },
  { id: 'coastal', name: 'Coastal', description: 'Breezy light blues & jute rugs', image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=800&auto=format&fit=crop' },
] as const;

export const EXTERIOR_DESIGN_STYLES = [
  { id: 'modern', name: 'Modern', description: 'Clean geometric lines & floor-to-ceiling glass' },
  { id: 'contemporary', name: 'Contemporary', description: 'State-of-the-art facade & warm ambient lighting' },
  { id: 'minimalist', name: 'Minimalist', description: 'Sleek monolithic concrete & wood slat cladding' },
  { id: 'luxury', name: 'Luxury', description: 'Grand marble entrance, limestone & cascading water' },
  { id: 'traditional', name: 'Traditional', description: 'Classic gables, brick facade & symmetrical windows' },
  { id: 'colonial', name: 'Colonial', description: 'Stately columns, portico entrance & shuttered windows' },
  { id: 'mediterranean', name: 'Mediterranean', description: 'Terracotta roof tiles, stucco walls & wrought iron' },
  { id: 'japanese', name: 'Japanese', description: 'Shou sugi ban dark burnt wood, cedar & zen garden' },
  { id: 'scandinavian', name: 'Scandinavian', description: 'Light timber cladding, steep roof & sunlit glass' },
  { id: 'industrial', name: 'Industrial', description: 'Dark steel beams, exposed brick & factory windows' },
  { id: 'rustic', name: 'Rustic', description: 'Natural fieldstone & heavy timber posts' },
  { id: 'victorian', name: 'Victorian', description: 'Ornate gingerbread trim, turret towers & steep gables' },
  { id: 'tropical', name: 'Tropical', description: 'Overhanging thatch roof, teak louvers & palm foliage' },
  { id: 'eco-friendly', name: 'Eco-friendly', description: 'Living green roof, solar panels & sustainable timber' },
] as const;

export const COLOR_PALETTES = [
  { slug: 'white', name: 'White', colors: ['#FFFFFF', '#F8F9FA', '#E9ECEF'] },
  { slug: 'beige', name: 'Beige', colors: ['#F5F5DC', '#E6D7C3', '#C2A68C'] },
  { slug: 'black', name: 'Black', colors: ['#1C1C1E', '#2C2C2E', '#3A3A3C'] },
  { slug: 'grey', name: 'Grey', colors: ['#8E8E93', '#AEAEB2', '#D1D1D6'] },
  { slug: 'earth-tone', name: 'Earth Tone', colors: ['#8C6D58', '#A0522D', '#D2B48C'] },
  { slug: 'warm-wood', name: 'Warm Wood', colors: ['#8B4513', '#A0522D', '#CD853F'] },
  { slug: 'dark-theme', name: 'Dark Theme', colors: ['#121212', '#1E1E1E', '#2D2D2D'] },
  { slug: 'blue', name: 'Blue', colors: ['#1B263B', '#415A77', '#778DA9'] },
  { slug: 'green', name: 'Green', colors: ['#2D5A27', '#4E7C48', '#8FBC8F'] },
  { slug: 'neutral', name: 'Neutral', colors: ['#E5E5E0', '#D3D3CB', '#B0B0A8'] },
] as const;

export const MOODS = [
  'Cozy',
  'Luxury',
  'Elegant',
  'Warm',
  'Bright',
  'Minimal',
  'Professional',
  'Creative',
  'Relaxing',
  'Modern',
  'Premium',
  'Family Friendly',
] as const;

export const BUDGET_LEVELS = [
  { slug: 'low', name: 'Low', description: 'Affordable budget-friendly interior solutions (IKEA / DIY).' },
  { slug: 'medium', name: 'Medium', description: 'Balanced mid-range budget with commercial quality furnishings.' },
  { slug: 'premium', name: 'Premium', description: 'High-end designer furniture & custom wood finishes.' },
  { slug: 'luxury', name: 'Luxury', description: 'Bespoke luxury with marble, brass & custom artisan craft.' },
] as const;

export const ROOM_TYPES = [
  'Living room',
  'Open Kitchen Living Room',
  'Bedroom',
  'Guest Bedroom',
  'Kids Room',
  'Nursery',
  'Bathroom',
  'Kitchen',
  'Dining room',
  'Formal Dining Room',
  'Attic',
  'Study room',
  'Home office',
  'Family Room',
  'Gaming room',
  'Home Theater',
  'Laundry Room',
  'Utility Room',
  'Pet Room',
  'Lounge',
  'Walk-in Closet',
  'Playroom',
  'Reading Nook',
  'Sauna',
  'Man Cave',
  'Foyer',
  'Prayer room',
  'Wine Cellar',
  'Sunroom',
  'Home Spa',
  'Mudroom',
  'Craft Room',
  'Dressing Room',
  'Home Bar',
  'Library',
  'Art Studio',
  'Yoga Studio',
  'Photo Studio',
  'Multimedia Room',
  'Music Room',
  'Home Gym',
  'Balcony',
  'Outdoor Kitchen',
  'Greenhouse',
  'She Shed',
  'Conservatory',
  'Rooftop Terrace',
  'Office',
  'Working Space',
  'Coworking space',
  'Meeting room',
  'Workshop',
  'Fitness gym',
  'Coffee shop',
  'Clothing store',
  'Restaurant',
  'Science Laboratory',
  'Wedding Room',
  'Hotel lobby',
  'Hotel room',
  'Hotel bathroom',
  'Exhibition space',
  'Onsen',
  'Auditorium',
  'Medical Exam Room',
  'Reception Area',
] as const;

export const BUILDING_TYPES = [
  'House',
  'Villa',
  'Apartment',
  'Office',
  'Commercial Building',
  'Shop',
  'Hotel',
  'Restaurant',
  'School',
  'Hospital',
  'Warehouse',
  'Farm House',
  'Cottage',
  'Beach House',
  'Cabin',
] as const;

export const ROOF_TYPES = [
  'Flat Roof',
  'Sloped Roof',
  'Gable Roof',
  'Hip Roof',
  'Terrace Roof',
] as const;

export const LIGHTING_OPTIONS = [
  'Warm',
  'Cool',
  'Luxury Lighting',
  'Landscape Lighting',
  'Hidden LED',
  'Wall Lights',
  'Cozy & Warm',
  'Bright & Natural',
  'Dramatic Mood',
] as const;

export const ENVIRONMENTS = [
  'City',
  'Village',
  'Beach',
  'Forest',
  'Mountain',
  'Snow',
  'Lake Side',
  'Desert',
  'Countryside',
] as const;

export const TIMES_OF_DAY = [
  'Morning',
  'Afternoon',
  'Golden Hour',
  'Sunset',
  'Night',
  'Rainy',
  'Snow',
] as const;
